# Prerequisite for installing longhorn.
#sudo apt update
#sudo apt install -y open-iscsi nfs-common
#sudo systemctl enable --now iscsid

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.12.1 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          httproute:
            enabled: true
            parentRefs:
              - name: traefik-gateway
                namespace: traefik
            hostnames:
              - longhorn.salmanisha.com
            path: /
            pathType: PathPrefix
            annotations:
              custom-annotation: "value"
          preUpgradeChecker:
            jobEnabled: false
          metrics:
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: prometheus
          
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
