apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content-lh
  namespace: blog
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn    
  resources:
    requests:
      storage: 10Gi             